dist: xenial

language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_326cdccd9729_key -iv $encrypted_326cdccd9729_iv -in nr-site.enc -out nr-site -d

install:
  - npm install

script:
  - npm run build
  - npm run generate

deploy:
  provider: pages:git
  local_dir: dist
  skip_cleanup: true
  deploy_key: nr-site
  edge: true # opt in to dpl v2
  keep_history: true
  on:
    branch: master