dist: xenial

language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build
  - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 7c0474c16001f33d37aea08e7e27a9f0690a6c38
  keep_history: true
  on:
    branch: master
