dist: xenial

language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

before_install: openssl aes-256-cbc -K $encrypted_ac8c84629a34_key -iv $encrypted_ac8c84629a34_iv -in srgyBIm8jYWywfKffrWN0Q -out nr-website -d

install:
  - npm install

script:
  - npm run build
  - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
